### ISSUE TITLE
The user should be able to log out

### ISSUE THREAD

**Issue by JamesTeague** [JamesTeague/ubiquitous-train#11]
Once logged in the user should have a way of logging out.

**Comment by gpwilson** [comment]
@JamesTeague Seems to be issue with signing out once signed in with Google. It will appear signed out (can see sign in screen) for a moment then it looks like Google signs the user back in. Is that a known issue and/or something you want to address?

**Comment by gpwilson** [comment]
Note: For testing purposes, can get around the issue by removing permissions on Google [here](https://myaccount.google.com/permissions) and signing out from Retreat.

**Comment by JamesTeague** [comment]
@gpwilson, it is a known issue but I have no idea how to prevent that from happening. If you have any thoughts or resources, please let me know. My original thought was to remove the Google sign in all together and force email and password. Thoughts on that?

**Comment by gpwilson** [comment]
@JamesTeague I think removing Google sign in would be fine if not able to find solution to the Google sign out issue. Could be added back as an enhancement further down the line if desired?

**Comment by gpwilson** [comment]
Am able to sign out when signed in with email/password.

@JamesTeague Should this ticket be closed and a new ticket created to track Google sign out?

**Comment by JamesTeague** [comment]
Leave it open for now until there is a resolution.

**Comment by JamesTeague** [comment]
I think there should be some information to be gained from [this link on stackoverflow](https://stackoverflow.com/questions/40983266/how-do-i-prevent-google-oauth-from-auto-signing-in). We should try this out here and see what results we can get. This would probably require some extensive testing before deploying.

**Comment by gpwilson** [comment]
Signed in with Google and was able to successfully sign out. Reloaded the page. Was not automatically signed in with Google (as expected). Was able to sign in with email/password. Signed out. Was able to sign in with Google. Signed out. 
Status: Pass
