### ISSUE TITLE
The system should have a footer on the page

### ISSUE THREAD

**Issue by JamesTeague** [JamesTeague/ubiquitous-train#18]
All pages should have a footer on the page. This should have a support email and a link to the project to allow users to be able to submit an issue should something need to be fixed.

**Comment by gpwilson** [comment]
Footer is visible on web browser and mobile. Formatting on mobile is a little odd:
![image](https://user-images.githubusercontent.com/13142535/36358282-2939f84e-14da-11e8-8769-494722122eb1.png)

@JamesTeague Links are functional on mobile so up to you if you care about the formatting!

**Comment by JamesTeague** [comment]
See https://github.com/JamesTeague/ubiquitous-train/issues/20#issuecomment-366558739. Same issue as above with https://github.com/JamesTeague/ubiquitous-train/issues/18#issuecomment-366558580 but more context on why this should be fixed.

**Comment by JamesTeague** [comment]
There is still an issue with the footer. It should never under any circumstance cover up any content in the body of the page. We need to do something so that it does not happen on mobile. This may mean removing it from mobile or removing it completely. For now, we should try formatting it better so that when the screen condenses there is still space between all content in the body and the footer.
