### ISSUE TITLE
The viewport on mobile seems off

### ISSUE THREAD

**Issue by JamesTeague** [JamesTeague/ubiquitous-train#20]
The pages are rendering within the frame on mobile, but the scaling seems off. There should be a way to fix this to make it look more appropriate on mobile devices.

**Comment by gpwilson** [comment]
Sign In button is getting stuck behind the footer:
![image](https://user-images.githubusercontent.com/13142535/36358317-997323e2-14da-11e8-8ee8-ca91e4994bae.png)

@JamesTeague Again up to you, although I think this is more "annoying" than the odd footer spacing.

**Comment by JamesTeague** [comment]
Because this seems to be a footer issue, I think this will fall under #18. So I will close and reference this comment on that issue. The original motivation for this particular issue seems to be resolved. The input fields are actually big enough to use on the mobile.
