### ISSUE TITLE
User should not be able to log out if they are not logged in

### ISSUE THREAD

**Issue by JamesTeague** [JamesTeague/ubiquitous-train#21]

**Comment by gpwilson** [comment]
Can still see log out button while not signed in:
![image](https://user-images.githubusercontent.com/13142535/36358077-0ea03cfe-14d6-11e8-9c1a-f95d0d0e4a59.png)

**Comment by gpwilson** [comment]
Log Out button appears disabled, but seems to trigger something (perhaps only a reload?) when clicked. Would it be better to remove the button completely when a user is not signed in?

**Comment by JamesTeague** [comment]
That's a much better idea, will implement.

**Comment by JamesTeague** [comment]
9dca0fd should have been referencing this issue. This should fix what was discussed [here](https://github.com/JamesTeague/ubiquitous-train/issues/21#issuecomment-366558934).

**Comment by gpwilson** [comment]
No Log Out button is visible when user is not signed in:
Status: Pass

![image](https://user-images.githubusercontent.com/13142535/36935249-87fc307a-1ec3-11e8-9c8f-d967ff68ca4a.png)
