### ISSUE TITLE
The system should warn users of login errors

### ISSUE THREAD

**Issue by JamesTeague** [JamesTeague/ubiquitous-train#26]
For example, if a user enters the wrong username or wrong password, the error is logged to the console, the user is never alerted and the page hangs. This probably has to do with the response object not being sent back on error. We should figure out a way to send back the error as an alert, preferably as a Bootstrap alert but we may have to explore different options.

We really should have a standard method of handling errors on the backend server side that knows how to bubble up errors to the front end and show them appropriately. So all errors can take that path no matter where they happen.

**Comment by gpwilson** [comment]
Scenarios tested:
Unregistered email/password
Entered email but no password
Registered email but wrong password

Received same error message for all scenarios:
![image](https://user-images.githubusercontent.com/13142535/36935408-736dfb5a-1ec5-11e8-93bd-ca59f34fe58b.png)

Status: Pass
