### ISSUE TITLE
The system should have a login page

### ISSUE THREAD

**Issue by JamesTeague** [JamesTeague/ubiquitous-train#4]
The system should have a landing page for users to log in. This page, at the minimum, should have buttons for Google and Twitter.

**Comment by JamesTeague** [comment]
The layout out of the page should be reviewed as well. Suggestions are welcome and are needed.

**Comment by JamesTeague** [comment]
I have found a prebuilt Firebase UI. I think that should be implemented here instead of building a view using bootstrap. There should be less to maintain and because the app won't support any authentication that is not through Firebase, I think this is a good route to take.

**Comment by JamesTeague** [comment]
After implementing the firebaseui, because of the implementation of it authenticating on the front end does not appear to authenticate a user on the server side. I tried to pass back the relevant information to authenticate again on the back end and was unsuccessful. Rather than continue with using firebaseui as the method. I will try to style it as the firebaseui UI and render the view from the server and still authenticate on the back end. This seems like a reasonable compromise to get the look I want and get away from serving a static page. This should also meet the requirement of having a user authenticated on the back end.

**Comment by gpwilson** [comment]
Sign In page provides ability to sign in with Google, sign in with email/password, or sign up for an account. 

Status: PASS
